name: fyd
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  geolocator: ^5.1.4+2
  google_maps_flutter: ^0.4.0
  cloud_firestore: ^0.12.0
  firebase_auth: ^0.10.0
  modal_progress_hud: ^0.1.3
  geoflutterfire: ^2.0.3+5
  flutter_datetime_picker: ^1.2.8
  intl: ^0.16.0
  jiffy: ^2.1.2
  rflutter_alert: ^1.0.3
  percent_indicator: ^2.1.1+1
  smooth_star_rating: 1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/img.png


fonts:
    - family: Cabin
      fonts:
        - asset:fonts/cabin-Regular.ttf
        
    - family: Lobester Two
      fonts:
        - asset: fonts/LobsterTwo-Regular.ttf

module:   
  androidX: true // Add this line.

  # To add assets to your application, add an assets section, like this:
 
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Noto Sans
  #     fonts:
  #       - asset: fonts/NotoSans-Regular.ttf
  #       - asset: fonts/NotoSans-Bold.ttf
  #         # weight: bold
  
        
    #       weight: 700   

    # - family: NotoSans
    #   fonts:
    #     - asset: fonts/LobsterTwo-Regular.ttf
        
    #       weight: 700   
  #         style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
